version: '3'

services:
    technician-route-planner-file-server:
        build: ./src/file-server
        ports:
            - "8080:8080"
        depends_on:
            - db
        container_name: technician-route-planner-file-server
        volumes:
            - tech-router-front-end-dist:dist
    db:
        image: mongo
        container_name: technician-route-planner-mongo

    vue-technician-route-planner:
        build: ./src/client
        container_name: vue-technician-route-planner
        volumes:
            - tech-router-front-end-dist:/vue-technician-route-planner/dist
            - ./vuesrc:/vue-technician-route-planner/src
volumes:
  tech-router-front-end-dist:
