/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.technicianRoutePlanner.RoutePlannerReply', null, global);
goog.exportSymbol('proto.technicianRoutePlanner.RoutePlannerRequest', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.technicianRoutePlanner.RoutePlannerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.technicianRoutePlanner.RoutePlannerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.technicianRoutePlanner.RoutePlannerRequest.displayName = 'proto.technicianRoutePlanner.RoutePlannerRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.technicianRoutePlanner.RoutePlannerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.technicianRoutePlanner.RoutePlannerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.technicianRoutePlanner.RoutePlannerRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.technicianRoutePlanner.RoutePlannerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    routename: jspb.Message.getField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.technicianRoutePlanner.RoutePlannerRequest}
 */
proto.technicianRoutePlanner.RoutePlannerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.technicianRoutePlanner.RoutePlannerRequest;
  return proto.technicianRoutePlanner.RoutePlannerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.technicianRoutePlanner.RoutePlannerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.technicianRoutePlanner.RoutePlannerRequest}
 */
proto.technicianRoutePlanner.RoutePlannerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRoutename(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.technicianRoutePlanner.RoutePlannerRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.technicianRoutePlanner.RoutePlannerRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.technicianRoutePlanner.RoutePlannerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.technicianRoutePlanner.RoutePlannerRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = jspb.Message.getField(this, 1);
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.technicianRoutePlanner.RoutePlannerRequest} The clone.
 */
proto.technicianRoutePlanner.RoutePlannerRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.technicianRoutePlanner.RoutePlannerRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * required string routeName = 1;
 * @return {string}
 */
proto.technicianRoutePlanner.RoutePlannerRequest.prototype.getRoutename = function() {
  return /** @type {string} */ (!this.hasRoutename() ? "" : jspb.Message.getField(this, 1));
};


/** @param {string|undefined} value  */
proto.technicianRoutePlanner.RoutePlannerRequest.prototype.setRoutename = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.technicianRoutePlanner.RoutePlannerRequest.prototype.clearRoutename = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.technicianRoutePlanner.RoutePlannerRequest.prototype.hasRoutename = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.technicianRoutePlanner.RoutePlannerReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.technicianRoutePlanner.RoutePlannerReply.repeatedFields_, null);
};
goog.inherits(proto.technicianRoutePlanner.RoutePlannerReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.technicianRoutePlanner.RoutePlannerReply.displayName = 'proto.technicianRoutePlanner.RoutePlannerReply';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.technicianRoutePlanner.RoutePlannerReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.technicianRoutePlanner.RoutePlannerReply.prototype.toObject = function(opt_includeInstance) {
  return proto.technicianRoutePlanner.RoutePlannerReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.technicianRoutePlanner.RoutePlannerReply} msg The msg instance to transform.
 * @return {!Object}
 */
proto.technicianRoutePlanner.RoutePlannerReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    linenumbersList: jspb.Message.getRepeatedFloatingPointField(msg, 1),
    sizeofclickedcellsmap: +jspb.Message.getField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.technicianRoutePlanner.RoutePlannerReply}
 */
proto.technicianRoutePlanner.RoutePlannerReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.technicianRoutePlanner.RoutePlannerReply;
  return proto.technicianRoutePlanner.RoutePlannerReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.technicianRoutePlanner.RoutePlannerReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.technicianRoutePlanner.RoutePlannerReply}
 */
proto.technicianRoutePlanner.RoutePlannerReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.getLinenumbersList().push(value);
      msg.setLinenumbersList(msg.getLinenumbersList());
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSizeofclickedcellsmap(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.technicianRoutePlanner.RoutePlannerReply} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.technicianRoutePlanner.RoutePlannerReply.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.technicianRoutePlanner.RoutePlannerReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.technicianRoutePlanner.RoutePlannerReply.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getLinenumbersList();
  if (f.length > 0) {
    writer.writeRepeatedDouble(
      1,
      f
    );
  }
  f = jspb.Message.getField(this, 2);
  if (f != null) {
    writer.writeDouble(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.technicianRoutePlanner.RoutePlannerReply} The clone.
 */
proto.technicianRoutePlanner.RoutePlannerReply.prototype.cloneMessage = function() {
  return /** @type {!proto.technicianRoutePlanner.RoutePlannerReply} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated double lineNumbers = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<number>}
 */
proto.technicianRoutePlanner.RoutePlannerReply.prototype.getLinenumbersList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/** @param {Array.<number>} value  */
proto.technicianRoutePlanner.RoutePlannerReply.prototype.setLinenumbersList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


proto.technicianRoutePlanner.RoutePlannerReply.prototype.clearLinenumbersList = function() {
  jspb.Message.setField(this, 1, []);
};


/**
 * required double sizeofclickedcellsmap = 2;
 * @return {number}
 */
proto.technicianRoutePlanner.RoutePlannerReply.prototype.getSizeofclickedcellsmap = function() {
  return /** @type {number} */ (!this.hasSizeofclickedcellsmap() ? 0.0 : +jspb.Message.getField(this, 2));
};


/** @param {number|undefined} value  */
proto.technicianRoutePlanner.RoutePlannerReply.prototype.setSizeofclickedcellsmap = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.technicianRoutePlanner.RoutePlannerReply.prototype.clearSizeofclickedcellsmap = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.technicianRoutePlanner.RoutePlannerReply.prototype.hasSizeofclickedcellsmap = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.technicianRoutePlanner);
